---
title: "data_visualization"
author: "Yifan Duan"
date: "01/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning = FALSE}
library(ggplot2)
library(dplyr)
library(ggmap)
library(mapproj)
```

```{r}
#initialize the data
dat <- read.csv("./input/info.csv")

dat$length <- as.factor(dat$length)
dat <- mutate(dat, host = gsub("([A-Z].*) .*", "\\1", dat$host))
dat <- mutate(dat, release_year = gsub("(\\d+)-.*", "\\1", dat$release_date))
```

```{r}
country_df <- data.frame(table(dat$country))
rownames(country_df) <- country_df$Var1
country_df$region <- rownames(country_df)

world_map <- map_data("world")
collection_map <- left_join(world_map, country_df, by = "region")

# Create the map
svg(filename = './figures/location.svg')
ggplot(collection_map, aes(long, lat, group = group))+
  geom_polygon(aes(fill = Freq), color = "white") +
  scale_fill_viridis_c(option = "C")
dev.off()
```

```{r}
# release year
svg(filename = './figures/release_year.svg')
ggplot(dat, aes(x = as.numeric(collection_date))) + geom_bar() +
  scale_x_continuous(name = "Collection date", breaks = seq(1950, 2000, by = 5))
dev.off()
```

```{r}
# genome length
svg(filename = './figures/genome_length.svg')
ggplot(dat, aes(x = "", y = length, fill = length)) + 
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start = 0) + theme_void() + ggtitle("Genome Length")
dev.off()
```

```{r}
# host
host_count <- count(dat, host)
common_name <- c("Unknown", "Mosquito (Aedes)", "Bird", "Crow", "Mosquito (Culex)", 
                 "Mosquito (Cuclicidae)", "Mosquito (Culiseta)", "Ticks (Dermacentor)", "Horse",
                 "Human", "Ticks (Hyalomma)", "Oriolus (Bird)", "Ticks (Ornithodoros)", "Fruit bat",
                 "Tissue culture")
species <- c("Unknown", "Mosquito", "Bird", "Bird", "Mosquito", "Mosquito", "Mosquito", "Ticks",
             "Horse", "Human", "Ticks", "Bird", "Ticks", "Bat", "Tissue")

host_count <- cbind(host_count, common_name, Species = as.factor(species))

svg(filename = './figures/host.svg')
host_count %>% ggplot(aes(x = reorder(common_name, n), y = n, fill = Species)) + 
  geom_col() + coord_flip() + 
  scale_x_discrete(name = "Species") + scale_y_continuous(name = "Count")
dev.off()
```

```{r}
# protein percentage identity matrix
data_CDS <- read.table('./input/pim.txt', header = F, sep = "")
rnames <- data_CDS[,1]
data_CDS2 <- data.matrix(data_CDS[, 2:ncol(data_CDS)])
rownames(data_CDS2) <- rnames
colnames(data_CDS2) <- rnames

#Set the colour scheme
require(RColorBrewer)
my_palette = colorRampPalette(c("white", "blue"))(n = 11)

#Set other variables
require(gplots)

#Prepare heatmaps
svg(filename = './figures/aai.svg')
my_palette = colorRampPalette(c("white", "dark blue"))(n = 5)
heatmap.2(data_CDS2, trace = c("none"), density.info = c("none"), 
          breaks = c(90, 92, 94, 96, 98, 100), col = my_palette, 
          lmat = matrix(c(4,2,3,1), nrow = 2, ncol = 2), key = T, labRow = rnames, labCol = rnames)
dev.off()
```

